ingress:
  enabled: true
  path: /grafana

grafana:
  # Set the root URL path
  grafana.ini:
    server:
      root_url: http://20.223.96.100/grafana
      serve_from_sub_path: true
  # dashboardProviders:
  #   dashboardPath: /grafana
