apiVersion: apps/v1
kind: Deployment
metadata:
  name: gv-front-deployment
  labels:
    app: gv-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gv-front
  template:
    metadata:
      labels:
        app: gv-front
    spec:
      containers:
      - name: gv-front
        image: mateduard/k8s-cluster-front:1.5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 25
          periodSeconds: 20
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 18
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            memory: "200Mi"      # Minimum memory guaranteed to the container
            cpu: "100m"          # Minimum CPU guaranteed (350 millicores, or 0.35 CPU)
          limits:
            memory: "250Mi"        # Maximum memory the container can use
            cpu: "150m"
        env:
        - name: VITE_BACK_PORT
          value: "80"           # port service backend (in this case, ingress public exposed port, as the requests are redirected by path and traffic rules)
        - name: VITE_FRONT_PORT
          value: "80"             # port service frontend (in this case, ingress public exposed port, as the requests are redirected by path and traffic rules)
        - name: VITE_BACK_SERVICE
          value: 20.13.206.85     # ip static ingress
        - name: VITE_FRONT_SERVICE
          value: 20.13.206.85     # ip static ingress